# Generated by Django 3.2.8 on 2021-10-30 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subscrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=200)),
                ('Tempid', models.IntegerField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Tempid', models.IntegerField(max_length=100)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('expirationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('postitionInList', models.IntegerField()),
                ('muted', models.BooleanField()),
                ('SubscriptionList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subscrap.subscriptionlist')),
            ],
        ),
    ]
