# Generated by Django 3.2.8 on 2021-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0002_subscriptionitem_subscriptionlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='Tempid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionlist',
            name='Tempid',
            field=models.IntegerField(),
        ),
    ]
