# Generated by Django 3.2.8 on 2021-11-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0003_auto_20211029_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlist',
            name='Tempid',
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='cyclePeriod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='Tempid',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
