# Generated by Django 3.2.8 on 2021-11-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0004_auto_20211102_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='Tempid',
        ),
    ]
