# Generated by Django 3.2.8 on 2021-11-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0006_auto_20211105_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='cyclePeriod',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='postitionInList',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
