# Generated by Django 3.2.8 on 2021-11-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0007_auto_20211105_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlist',
            name='author',
        ),
    ]
