# Generated by Django 3.2.8 on 2021-11-06 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0010_subscriptionitem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='author',
        ),
    ]
