# Generated by Django 3.2.8 on 2021-11-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0011_remove_subscriptionitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='expirationDate',
            field=models.DateTimeField(),
        ),
    ]
