# Generated by Django 3.2.8 on 2021-11-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0013_subscriptionitem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='SubscriptionList',
        ),
    ]
