# Generated by Django 3.2.8 on 2021-11-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0014_remove_subscriptionitem_subscriptionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionitem',
            name='SubscriptionList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Subscrap.subscriptionlist'),
            preserve_default=False,
        ),
    ]
