# Generated by Django 3.2.8 on 2021-11-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0015_subscriptionitem_subscriptionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionitem',
            name='author',
        ),
    ]
