# Generated by Django 3.2.8 on 2021-11-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0004_auto_20211104_1737'),
        ('Subscrap', '0008_alter_subscriptionitem_price'),
        ('Subscrap', '0016_remove_subscriptionitem_author'),
    ]

    operations = [
    ]
