# Generated by Django 3.2.8 on 2021-11-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscrap', '0017_merge_20211106_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='cyclePeriod',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
